### ISSUE TITLE
Always returning ConsentType.UNKNOWN

### ISSUE THREAD

**Issue by joshmatta** [Skyost/FlutterFundingChoices#1]
FlutterFundingChoices.requestConsentInformation() always returns ConsentInformation with ConsentType.UNKNOWN
no matter the choice chosen by the user. But when we choose do not consent the ads doesn't load at all.

After searching for the issue I found this https://www.reddit.com/r/adops/comments/ifh6n9/anybody_using_google_funding_choices_for_gdpr_cmp

I would like to know if you faced a similar problem when you implemented this plugin for your apps and if so how did you solve it.

**Comment by Skyost** [comment]
> I would like to know if you faced a similar problem when you implemented this plugin for your apps and if so how did you solve it.

Yes I found a similar problem on my Android emulator. But, quoting your provided link :

> To address your concern, this behavior is expected - window.googlefc.getConsentStatus() ​will always return window.googlefc.ConsentStatusEnum.UNKNOWN if you're using the IAB TCF v2 framework. This status is only applicable if you're using the simplified Google GDPR consent framework.

(and I think it's similar on Android & iOS UMP SDKs)

But I agree that Google is not precise on that point.

**Comment by Skyost** [comment]
Closed due to inactivity.

**Comment by Kobatsu** [comment]
I am also facing this issue now. I have read the Reddit post but I still don't understand what it means...

I have the ConsentType UNKNOWN and the ConsentStatus REQUIRED even after accepting every single think I could check.

There seem to be many things written in the Logs :
```
[. . .]
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_CmpSdkVersion] 1
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_PolicyVersion] 2
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_gdprApplies] 1
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_PublisherCC] FR
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_PurposeOneTreatment] 0
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_UseNonStandardStacks] 0
D/UserMessagingPlatform(13770): Writing to storage: [IABTCF_VendorConsents] 0
[. . .]
```

I found this about the IAB TCF v2 which may explain what they are : https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md

But I don't know if I have to read some value in the SharedPreferences to know if the user allowed me to use personalized ads and if so, which shared preference value ?

The more I see about the UMP the more I get lost 😞 How did you manage to use the UMP SDK?

**Comment by Skyost** [comment]
> I have read the Reddit post but I still don't understand what it means...

It just means that the `consentType` getter is useless for the moment because it always return a `UNKNOWN` status. Pretty simple, no ? 😄

> There seem to be many things written in the Logs

As you said, in the IAB specs, the CMP has to write the user consent data using very specific `SharedPreferences` key/value pairs (on Android) ; this is what is written in the logs.

> But I don't know if I have to read some value in the SharedPreferences to know if the user allowed me to use personalized ads and if so, which shared preference value ?

AdMob will read it for you ! With Funding Choices, you can't read the user consent data (except the output of `requestConsentInformation`) ; but it's very specific to Funding Choices. For instance, Ogury allows you to [check which purposes have been accepted by the user](https://ogury-ltd.gitbook.io/choice-manager-android/advanced-usages/gdpr/transmit-the-user-consent#transmit-purpose-specific-consent-status).

> The more I see about the UMP the more I get lost 😞 How did you manage to use the UMP SDK?

I don't use it because of #4 tbh.

**Comment by Kobatsu** [comment]
> @Kobatsu
> 
> > I have read the Reddit post but I still don't understand what it means...
> 
> It just means that the `consentType` getter is useless for the moment because it always return a `UNKNOWN` status. Pretty simple, no ? 😄
> 
> > There seem to be many things written in the Logs
> 
> As you said, in the IAB specs, the CMP has to write the user consent data using very specific `SharedPreferences` key/value pairs (on Android) ; this is what is written in the logs.
> 
> > But I don't know if I have to read some value in the SharedPreferences to know if the user allowed me to use personalized ads and if so, which shared preference value ?
> 
> AdMob will read it for you ! With Funding Choices, you can't read the user consent data (except the output of `requestConsentInformation`) ; but it's very specific to Funding Choices. For instance, Ogury allows you to [check which purposes have been accepted by the user](https://ogury-ltd.gitbook.io/choice-manager-android/advanced-usages/gdpr/transmit-the-user-consent#transmit-purpose-specific-consent-status).
> 
The Ogury way seems better for the user choices but doesn't seem to have as much functionnalities in the ads area on Flutter as admob, but thank you for the exemple and all the explanations! I will have to find an other way to allow Crashlytics & Analytics.

> > The more I see about the UMP the more I get lost 😞 How did you manage to use the UMP SDK?
> 
> I don't use it because of #4 tbh.

Yeah, I wasn't there yet. I may ending up by disabling personalized ads while it's not fixed, as it was suggested on SO.

**Comment by Skyost** [comment]
@Kobatsu I've ended up implementing my own dialog for personalized ads consentment. If you're interested, you can find the source code [here](https://github.com/Skyost/Bacomathiques/blob/app/lib/app/dialogs/consent.dart) (it's not perfect, but it's almost ready to use in any project).

**Comment by Tobivaria** [comment]
I also went down the UMP rabbit hole... There is so much information and I am getting more confused.

Are these statements correct? :
- we can use this plugin and UMP, but it's still incomplete
- admob automatically picks personalized / non personalized ads, based on user decision
- even though the admob plugin has the option to serve personalized ads, it would just ignore this setting if I set admob to serve personalized ads as UMP knows better

**Comment by Skyost** [comment]
@Tobivaria 

> we can use this plugin and UMP, but it's still incomplete

I don't know, it depends on Google plans. I personally think that Funding Choices is far from being complete tbh, but it's _usable_.

> admob automatically picks personalized / non personalized ads, based on user decision

Yes. Based on user decision, it can also choose to not serve any ad at all (see #4) which is the biggest problem of Funding Choices for me.

> even though the admob plugin has the option to serve personalized ads, it would just ignore this setting if I set admob to serve personalized ads as UMP knows better

The AdMob plugin only has the option to serve non-personalized ads (it's personalized by default). If you set this option, it should ignore those specified by UMP.

> Also in the UMP center, what of these 10 options need to be selected to serve personalized ads ?

See the section <q>Consent policies: Personalized & Non-Personalized Ads</q> of [this page](https://support.google.com/admob/answer/9760862?hl=en&ref_topic=9756841).
