### ISSUE TITLE
IOS build error: Parse Issue: Module flutter_funding_choices not found

### ISSUE THREAD

**Issue by Flajt** [Skyost/FlutterFundingChoices#14]
**Describe the bug**
Just tried to build my app for IOS in dev mode and it returns me the error.
The file file it opens up on clicking on the error is: `GeneratedPluginRegistrant.m`

**To Reproduce**
1. Open up app in Xcode
2. Click on the "play" button for building it
3. Wait for build

**Expected behavior**
Build successfully and launch app in emulator
**Screenshots**
![Bildschirmfoto 2021-07-13 um 00 54 28](https://user-images.githubusercontent.com/25278830/125365694-05a04380-e375-11eb-8a00-27e257d22187.png)

**Desktop:**
 - OS: Mac OS Catalina
 - Version: 10.15.7

**Smartphone:**
 - Device: iPhone 12 (Emulator)
 - OS: IOS
 - Version: NA

**Additional context**
There is a chance that I've messed configurations or so up, as this is my first time building for IOS.
My min IOS target or what it's called is 12.0. 
Notice: I ran also `flutter build ipa` before, which completed without errors, which is kinda odd that Xcode can't build it.

**Comment by Skyost** [comment]
Yeah it's something that happens with native iOS libraries. Try to run :

```
flutter clean
cd ios
pod update
```

**Comment by Flajt** [comment]
Now I feel stupid XD. Seems to have worked, at least no errors this time.
After you run `flutter clean` you also need to run `flutter pub get` again. Or else it will throw you an error.


So for anyone who might stumble across this later:
```sh
flutter clean
flutter pub get 
cd ios
pod update
```
