### ISSUE TITLE
Fatal Error on iOS

### ISSUE THREAD

**Issue by amitash** [Skyost/FlutterFundingChoices#5]
**Describe the bug**
A Funding Choices message appears on Android but not on iOS. I created the same message on the FC website for both platforms. On iOS, when trying to debug, I created a function to reset and then ask for consent again as follows:

`Future<void> resetConsentOptions() async {
    try {
      await FlutterFundingChoices.reset();
      ConsentInformation consentInfo =
          await FlutterFundingChoices.requestConsentInformation();
      if (consentInfo.isConsentFormAvailable &&
          consentInfo.consentStatus == ConsentStatus.REQUIRED) {
        await FlutterFundingChoices.showConsentForm();
      }
    } catch (e) {
      // Error Snackbar
    }
 }`

This crashes the app with the following message in the log:
`Fatal error: Unexpectedly found nil while unwrapping an Optional value: file flutter_funding_choices/SwiftFlutterFundingChoicesPlugin.swift, line 16
`

**To Reproduce**
Steps to reproduce the behaviour:
Described above

**Desktop (please complete the following information):**
 - MacOS Big Sur 11.0.1

**Smartphone (please complete the following information):**
 - iPhone 12 Pro Max iOS 14.3 Simulator

**Comment by Skyost** [comment]
Shouldn't be too hard to fix. I'll check it soon.

**Comment by Skyost** [comment]
It should be fixed now. Sadly, I currently do not have a Mac with me, so is it possible for you to test it before I release it on pub.dev ?

**Comment by amitash** [comment]
Indeed, it is fixed. Thanks!

**Comment by Skyost** [comment]
Top, I will send a release tomorrow ! :wink:
